# Generated by Django 2.1.5 on 2019-10-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aid', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'admin_details',
            },
        ),
        migrations.CreateModel(
            name='Card_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.CharField(max_length=20)),
                ('Uid', models.CharField(max_length=20)),
                ('card_type', models.CharField(max_length=200)),
                ('cardno', models.CharField(max_length=200)),
                ('cvv', models.CharField(max_length=10)),
                ('expiry', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'card_details',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.CharField(max_length=20)),
                ('Pname', models.CharField(max_length=200)),
                ('qty', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('Uid', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tid', models.CharField(max_length=20)),
                ('Uid', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.CharField(max_length=20)),
                ('pname', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('subcategory', models.CharField(max_length=10)),
                ('cost', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=200)),
                ('uemail', models.EmailField(max_length=254)),
                ('ucontact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('upassword', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
