# Generated by Django 2.1.5 on 2019-10-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOnlineTransactionFraudDetection', '0002_auto_20191023_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='img/images'),
        ),
    ]
