# Generated by Django 2.1.5 on 2019-11-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOnlineTransactionFraudDetection', '0003_auto_20191028_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cost',
            field=models.IntegerField(default=None),
        ),
    ]
