# Generated by Django 2.1.5 on 2019-11-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOnlineTransactionFraudDetection', '0004_auto_20191102_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_details',
            name='amount',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='total',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.IntegerField(default=None),
        ),
    ]
