# Generated by Django 2.1.5 on 2019-11-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOnlineTransactionFraudDetection', '0005_auto_20191102_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=None),
        ),
    ]
