# Generated by Django 2.1.5 on 2019-11-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOnlineTransactionFraudDetection', '0006_auto_20191102_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='ucontact',
            new_name='Expirydate',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='uid',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='uemail',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='uname',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='upassword',
        ),
        migrations.AddField(
            model_name='user_details',
            name='Card_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user_details',
            name='MaxTransAmount',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user_details',
            name='cvv',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user_details',
            name='mobile',
            field=models.IntegerField(default=None),
        ),
    ]
