# Generated by Django 2.1.5 on 2019-11-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOnlineTransactionFraudDetection', '0007_auto_20191104_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='total',
        ),
        migrations.AddField(
            model_name='order_details',
            name='TotalAmount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order_details',
            name='productList',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='order_details',
            name='quantity',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='status',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
