# Generated by Django 2.1.5 on 2019-11-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOnlineTransactionFraudDetection', '0009_auto_20191105_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='attempts',
            field=models.IntegerField(default=None),
        ),
    ]
