# Generated by Django 2.1.5 on 2019-11-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOnlineTransactionFraudDetection', '0011_auto_20191105_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='status',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
