# Generated by Django 2.1.5 on 2019-11-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOnlineTransactionFraudDetection', '0012_user_details_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='status',
            field=models.CharField(default='Unblocked', max_length=200),
        ),
    ]
