# Generated by Django 2.1.5 on 2019-11-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOnlineTransactionFraudDetection', '0013_auto_20191105_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Pid',
            field=models.CharField(max_length=200),
        ),
    ]
