# Generated by Django 2.1.5 on 2019-11-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOnlineTransactionFraudDetection', '0014_auto_20191106_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('Card_number', models.IntegerField(default=None)),
                ('cvv', models.IntegerField(default=None)),
                ('Issue', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'blockrequest',
            },
        ),
    ]
