# Generated by Django 2.1.5 on 2019-11-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOnlineTransactionFraudDetection', '0015_blockrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockrequest',
            name='Issue',
            field=models.CharField(max_length=1000),
        ),
    ]
